{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.printbeam",
    "module": "printbeam",
    "version": "0.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-metadata-0.1.0-alpha02.jar",
          "url": "printbeam-0.1.0-alpha02.jar",
          "size": 32810,
          "sha512": "df136b2f39bc7878b4038be998d49b0e7ab027971251d54bb1d5b94cb6fdedc9817709cd76515fd3d350ec116d82a43ac4699f97ff9f99ab94980f38bbd8337b",
          "sha256": "6d11c93b24a087fb3b05333bfeaad52b753842c224342144e9793f74378583fb",
          "sha1": "a7fb27d93459810017778a4ac5543de4d4bca3a2",
          "md5": "01911f484d6da9d2d84c94c692f3b041"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printbeam-android/0.1.0-alpha02/printbeam-android-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-android",
        "version": "0.1.0-alpha02"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printbeam-android/0.1.0-alpha02/printbeam-android-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-android",
        "version": "0.1.0-alpha02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iosarm64/0.1.0-alpha02/printbeam-iosarm64-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-iosarm64",
        "version": "0.1.0-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iosarm64/0.1.0-alpha02/printbeam-iosarm64-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-iosarm64",
        "version": "0.1.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iossimulatorarm64/0.1.0-alpha02/printbeam-iossimulatorarm64-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-iossimulatorarm64",
        "version": "0.1.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iossimulatorarm64/0.1.0-alpha02/printbeam-iossimulatorarm64-0.1.0-alpha02.module",
        "group": "dev.printbeam",
        "module": "printbeam-iossimulatorarm64",
        "version": "0.1.0-alpha02"
      }
    }
  ]
}
