{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printbeam/0.1.0-alpha04/printbeam-0.1.0-alpha04.module",
    "group": "dev.printbeam",
    "module": "printbeam",
    "version": "0.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-iosSimulatorArm64Main-0.1.0-alpha04.klib",
          "url": "printbeam-iossimulatorarm64-0.1.0-alpha04.klib",
          "size": 297825,
          "sha512": "14c34925ea541e31df28a64d749be90ae301696d3ae04528f3b8d695c1038b7059308d92866b2cb3b77515c581b47495f1dfd1fc41e6d8e8e1c99721f583414c",
          "sha256": "58627b7fead3b83e1fde4669c338f0c4e57002387a8b0b4aa607608736bc49de",
          "sha1": "4f4af9e51b83abfe4a86dee83c2509a7c9cccdc1",
          "md5": "20a2ad94063bd53be9d4ed6ffe06d566"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-iossimulatorarm64-0.1.0-alpha04-metadata.jar",
          "url": "printbeam-iossimulatorarm64-0.1.0-alpha04-metadata.jar",
          "size": 11133,
          "sha512": "180c947380e36ffa1ace94a8562a9e5dabf792138444e24d56458ed5678167c150817b16f446120cc17f5ae790e6183c33c178e2f1d315decf8f9bed457835c1",
          "sha256": "b8a00de73432e3e93b634ec9d8d4d434bf5c523ce2814c1a9ba46f760e91e660",
          "sha1": "284e5035c88947e5e43edc5ebd9673dba5367ee6",
          "md5": "f37b8b43c3fa8e025c57f0fcc913f0ce"
        }
      ]
    }
  ]
}
