{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.printbeam",
    "module": "printbeam",
    "version": "0.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-metadata-0.1.0-alpha01.jar",
          "url": "printbeam-0.1.0-alpha01.jar",
          "size": 31621,
          "sha512": "fa88c0e4ff2cc8734fcb5312e010e6c76738b7ccbb93cd3c187af6b2b6bd22e1d2139cd336011cd5c1dc5a9c64b216584e2146d7d6eaec28a298200a4886adb0",
          "sha256": "a0731e58cf2d8352ba7d4ace8f0aa9ccc1d1ec3ed10c96f626277aebff8a77b2",
          "sha1": "c40ecb0cb411b49e24f5bdaa670ba3908c3fbf94",
          "md5": "6d6c7809b69237d7354e9ef2a332c108"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printbeam-android/0.1.0-alpha01/printbeam-android-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-android",
        "version": "0.1.0-alpha01"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printbeam-android/0.1.0-alpha01/printbeam-android-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-android",
        "version": "0.1.0-alpha01"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iosarm64/0.1.0-alpha01/printbeam-iosarm64-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-iosarm64",
        "version": "0.1.0-alpha01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iosarm64/0.1.0-alpha01/printbeam-iosarm64-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-iosarm64",
        "version": "0.1.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iossimulatorarm64/0.1.0-alpha01/printbeam-iossimulatorarm64-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-iossimulatorarm64",
        "version": "0.1.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printbeam-iossimulatorarm64/0.1.0-alpha01/printbeam-iossimulatorarm64-0.1.0-alpha01.module",
        "group": "dev.printbeam",
        "module": "printbeam-iossimulatorarm64",
        "version": "0.1.0-alpha01"
      }
    }
  ]
}
