{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printbeam/0.1.0-alpha01/printbeam-0.1.0-alpha01.module",
    "group": "dev.printbeam",
    "module": "printbeam",
    "version": "0.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-iosArm64Main-0.1.0-alpha01.klib",
          "url": "printbeam-iosarm64-0.1.0-alpha01.klib",
          "size": 283031,
          "sha512": "effaa53e2bb387503762f917cd1d6af04bcaf514253a64ff413d417e7a6b3bfae382d85b0361e9306d72120c3210064de3f0e96dc57691add17d6cd15fc3fb8e",
          "sha256": "ccbd86b973a391daff3a12cd24cdfa7cde971f7890160766673da59bbcd500ce",
          "sha1": "8a50b35d0daebba1ecf93198cc4b46c7afd8fa2e",
          "md5": "4171b2c672894cc8a67863c2f6a4f6b6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "printbeam-iosarm64-0.1.0-alpha01-metadata.jar",
          "url": "printbeam-iosarm64-0.1.0-alpha01-metadata.jar",
          "size": 10669,
          "sha512": "8073f682f1bf695e73a7d548cf67a8173e30003ab1df0c886080674c6a416609593a894703af1b0723ad4cde78defc03d80745e869770484f970aff9af42977d",
          "sha256": "1fdb309aa8428825433c08f66a45d328ecf2b5061a14aff38328ca962f7b6ecd",
          "sha1": "ca38628365a48d3cada7dbf1806ad69e4cbb3341",
          "md5": "c7fb2bb7f879a8d4a676d54f1434c198"
        }
      ]
    }
  ]
}
